lib/auth_web/router.ex
defmodule AuthWeb.Router do
  use AuthWeb, :router

  import AuthWeb.UserAuth

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:put_root_layout, {AuthWeb.LayoutView, :root})
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(:fetch_current_user)
  end

  # / Main Home
  scope "/", AuthWeb do
    pipe_through(:browser)

    get("/", PageController, :index)

  end

  ## Feed (if logged)
  scope "/", AuthWeb do
    pipe_through([:browser, :require_authenticated_user])

    live("/home", FeedLive, :live_view) # route to feed ( /home or / )
  end

  ## Authentication routes
  scope "/", AuthWeb do
    pipe_through([:browser, :redirect_if_user_is_authenticated])
    get("/users/register", UserRegistrationController, :new) # route to
    post("/users/register", UserRegistrationController, :create) # form
    get("/users/log_in", UserSessionController, :new) # route to
    post("/users/log_in", UserSessionController, :create) # form
    get("/users/reset_password", UserResetPasswordController, :new)
    post("/users/reset_password", UserResetPasswordController, :create)
    get("/users/reset_password/:token", UserResetPasswordController, :edit)
    put("/users/reset_password/:token", UserResetPasswordController, :update)
  end

  # Settings Route
  scope "/", AuthWeb do
    pipe_through([:browser, :require_authenticated_user])

    get("/users/settings", UserSettingsController, :edit) # route to
    put("/users/settings", UserSettingsController, :update) # form
    get("/users/settings/confirm_email/:token", UserSettingsController, :confirm_email)

    get("/users/settings/profile", UserSettingsController, :edit_profile) # route to pagina p/ editar o perfil
    put("/users/settings/profile", UserSettingsController, :update_profile) # form
  end

  # Search Route
  scope "/", AuthWeb do
    pipe_through([:browser, :require_authenticated_user])
    live("/search", SearchLive)
  end

  # User's crud
  scope "/", AuthWeb do
    pipe_through([:browser])
    delete("/users/log_out", UserSessionController, :delete) # log-out
    get("/users/confirm", UserConfirmationController, :new)
    post("/users/confirm", UserConfirmationController, :create)
    get("/users/confirm/:token", UserConfirmationController, :edit)
    post("/users/confirm/:token", UserConfirmationController, :update)
  end

  # Profile Route
  scope "/", AuthWeb do
    pipe_through([:browser, :require_authenticated_user])
    live("/:username", ProfileLive) # route to profile ( /@username )
  end
end

lib/auth_web/controllers/user_session_controller.ex
defmodule AuthWeb.UserSessionController do
  use AuthWeb, :controller
  alias Auth.Accounts
  alias AuthWeb.UserAuth

  def new(conn, _params) do
    render(conn, "new.html", error_message: nil)
  end

  # Login
  def create(conn, %{"user" => user_params}) do
    %{"email" => email, "password" => password} = user_params

    if user = Accounts.get_user_by_email_and_password(email, password) do
      UserAuth.log_in_user(conn, user, user_params)
    else
      # In order to prevent user enumeration attacks, don't disclose whether the email is registered.
      render(conn, "new.html", error_message: "E-mail ou senha inválidos.")
    end
  end

  # Logout
  def delete(conn, _params) do
    conn
    |> put_flash(:info, "Desconectado com sucesso.")
    |> UserAuth.log_out_user()
  end
end

lib/auth_web/views/user_session_view.ex
defmodule AuthWeb.UserSessionView do
  use AuthWeb, :view
end

lib/auth_web/templates/user_session/new.html.heex
<section class="sec-h">
  <div class="glass mx-10 p-8 space-y-20 w-11/12 max-w-5xl">

    <h1 class="flex justify-center text-6xl md:text-7xl font-bold">
      Entrar
    </h1>

    <.form let={f} for={@conn} action={Routes.user_session_path(@conn, :create)} as={:user}>
      <%= if @error_message do %>
        <div class="alert alert-danger">
          <p><%= @error_message %></p>
        </div>
      <% end %>

      <%= label f, :email, "E-mail" %>
      <%= email_input f, :email, required: true %>

      <%= label f, :password, "Senha" %>
      <%= password_input f, :password, required: true %>

      <!-- <%= label f, :remember_me, "Mantenha-me conectado por 60 dias" %> -->
      <!-- <%= checkbox f, :remember_me, value: true %> -->

      <p class="decoration-blue-600">
        <!-- <%= link "Cadastrar", to: Routes.user_registration_path(@conn, :new) %> | -->
        <%= link "Esqueci a senha", to: Routes.user_reset_password_path(@conn, :new), class: "primary_btn"%>
      </p>

      <div class="flex py-4 items-center justify-center">
        <%= submit "Entrar", class: "primary_btn text-2xl md:text-3xl" %>
      </div>
    </.form>

  </div>
</section>