lib/auth_web/router.ex
defmodule AuthWeb.Router do
  use AuthWeb, :router

  import AuthWeb.UserAuth

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:put_root_layout, {AuthWeb.LayoutView, :root})
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(:fetch_current_user)
  end

  # / Main Home
  scope "/", AuthWeb do
    pipe_through(:browser)

    get("/", PageController, :index)

  end

  ## Feed (if logged)
  scope "/", AuthWeb do
    pipe_through([:browser, :require_authenticated_user])

    live("/home", FeedLive, :live_view) # route to feed ( /home or / )
  end

  ## Authentication routes
  scope "/", AuthWeb do
    pipe_through([:browser, :redirect_if_user_is_authenticated])
    get("/users/register", UserRegistrationController, :new) # route to
    post("/users/register", UserRegistrationController, :create) # form
    get("/users/log_in", UserSessionController, :new) # route to
    post("/users/log_in", UserSessionController, :create) # form
    get("/users/reset_password", UserResetPasswordController, :new)
    post("/users/reset_password", UserResetPasswordController, :create)
    get("/users/reset_password/:token", UserResetPasswordController, :edit)
    put("/users/reset_password/:token", UserResetPasswordController, :update)
  end

  # Settings Route
  scope "/", AuthWeb do
    pipe_through([:browser, :require_authenticated_user])

    get("/users/settings", UserSettingsController, :edit) # route to
    put("/users/settings", UserSettingsController, :update) # form
    get("/users/settings/confirm_email/:token", UserSettingsController, :confirm_email)

    get("/users/settings/profile", UserSettingsController, :edit_profile) # route to pagina p/ editar o perfil
    put("/users/settings/profile", UserSettingsController, :update_profile) # form
  end

  # Search Route
  scope "/", AuthWeb do
    pipe_through([:browser, :require_authenticated_user])
    live("/search", SearchLive)
  end

  # User's crud
  scope "/", AuthWeb do
    pipe_through([:browser])
    delete("/users/log_out", UserSessionController, :delete) # log-out
    get("/users/confirm", UserConfirmationController, :new)
    post("/users/confirm", UserConfirmationController, :create)
    get("/users/confirm/:token", UserConfirmationController, :edit)
    post("/users/confirm/:token", UserConfirmationController, :update)
  end

  # Profile Route
  scope "/", AuthWeb do
    pipe_through([:browser, :require_authenticated_user])
    live("/:username", ProfileLive) # route to profile ( /@username )
  end
end

lib/auth_web/live/feed/feed_live.ex
defmodule AuthWeb.FeedLive do
  use AuthWeb, :live_view
  alias Auth.{Accounts, Post, Comment, SimpleS3Upload}


  @impl true
  def mount(_params, session, socket) do
    if connected?(socket) do
      Post.subscribe()
      Comment.subscribe()
    end
    limite = 6
    user = Accounts.get_user_by_session_token(session["user_token"])
    posts_map =
      Post.get_posts(limite)
      |> Enum.reduce(%{}, fn post, acc -> Map.put(acc, post.id, post) end)

    {:ok,
      socket
      |> Phoenix.LiveView.assign(uploaded_files: [])
      |> Phoenix.LiveView.allow_upload(:img, accept: ~w(.png .jpg .jpeg), max_entries: 1, auto_upload: false, external: &SimpleS3Upload.presign_upload/2)
      |> assign(
        current_user: user,
        posts: posts_map,
        has_more_posts: true,
        text: "",
        error: ""
      ) #, temporary_assigns: [posts: []]
    }
  end


  @impl true
  def handle_info({:post_created, post}, socket) do
    updated_posts = Map.put(socket.assigns.posts, post.id, post)
    {:noreply, assign(socket, posts: updated_posts)}
  end

  @impl true
  def handle_info({:post_updated, updated_post}, socket) do
    updated_posts = Map.put(socket.assigns.posts, updated_post.id, updated_post)
    {:noreply, assign(socket, posts: updated_posts)}
  end

#  @impl true
#  def handle_info({:comment_created, _comment}, socket) do
#    {:noreply, update(socket, :posts, fn posts -> [post | posts] end)}
#  end

  @impl true
  def handle_event("save", %{"text" => text}, socket) do
    photo_url = get_photo_url(socket)

    Post.create_post(
      %{
        text: text,
        user_id: socket.assigns.current_user.id,
        photo_url: photo_url
      }
    )
    {:noreply, socket}
  end


  @impl true
  def handle_event("like", %{"post_id" => post_id}, socket) do
    {post_id, _} = Integer.parse(post_id)
    post = Map.get(socket.assigns.posts, post_id)
    current_user_id = socket.assigns.current_user.id

    updated_post = if current_user_id not in post.liked_by do
      Post.inc_like(post, current_user_id) # Add
    else
      Post.dec_like(post, current_user_id) # Remove
    end

    updated_posts = Map.put(socket.assigns.posts, updated_post.id, updated_post)
    {:noreply, assign(socket, posts: updated_posts)}
  end

  @impl true
  def handle_event("save_comment", %{"text-comment" => text_comment, "postid" => post_id}, socket) do
    %{
      user_id: socket.assigns.current_user.id,
      post_id: post_id,
      text: text_comment
    }
    |> Comment.create_comment()
    {:noreply, socket}
  end

  @impl true
  def handle_event("validate", %{"text" =>  input_text}, socket) do
      if socket.assigns.uploads.img.entries != [] do
        # Tratar o erro :not_accepted e :too_large, upload_errors não está retornando-os
        for err <- Phoenix.LiveView.Helpers.upload_errors(socket.assigns.uploads.img) do
          err |> error_to_string()
          |> IO.inspect()
        end
#        IO.inspect(socket.assigns.uploads.img.entries)
      end
    {:noreply, assign(socket, text: input_text)}
  end


  @impl true
  def handle_event("cancel-entry", %{"ref" => ref}, socket) do
    {:noreply, Phoenix.LiveView.cancel_upload(socket, :img, ref)}
  end

  @impl true
  def handle_event("load-more", _params, socket) do
    limite = 6
    last_post_id = socket.assigns.posts |> Map.keys |> List.first
    more_posts = Post.load_more_posts(last_post_id, limite)

    more_posts_map = Enum.reduce(more_posts, %{}, fn post, acc ->
      Map.put(acc, post.id, post)
    end)

    updated_posts = Map.merge(socket.assigns.posts, more_posts_map)
    has_more_posts = length(more_posts) == limite

    {:noreply, assign(socket, posts: updated_posts, has_more_posts: has_more_posts)}
  end


  defp get_photo_url(socket) do
    uploaded_file_url = consume_uploaded_entries(socket, :img, fn _, entry ->
      {:ok, SimpleS3Upload.entry_url(socket.assigns.current_user.id, entry)}
    end)
    url_or_nil(List.first(uploaded_file_url), nil)
  end
  defp url_or_nil(s3_url, photo_url) when is_nil(s3_url), do: photo_url
  defp url_or_nil(s3_url, _photo_url), do: s3_url

  @doc """
    Trata o erro vindo de um atom subsequente da função `upload_error` e retorna uma string contendo o significado do erro em português.
  """
  def error_to_string(:too_large), do: "Arquivo muito grande!"
  def error_to_string(:not_accepted), do: "Você selecionou um arquivo não aceito!"
  def error_to_string(:too_many_files), do: "Você selecionou muitos arquivos!"

end

lib/auth_web/live/live_helpers.ex
defmodule AuthWeb.LiveHelpers do
  import Phoenix.LiveView
  alias AuthWeb.Router.Helpers, as: Routes

  def assign_defaults(session, socket) do
    user = session["current_user"]
    IO.puts("ASSIGN DEFAULT")
    IO.inspect(user)
    socket = assign_new(socket, :current_user, fn ->
      user
    end)

    if is_nil(socket.assigns.current_user) do
      socket
        |> put_flash(:error, "É necessário realizar login para acessar essa página")
        |> redirect(to: Routes.user_session_path(socket, :new))
    else
      socket
    end
  end

end

lib/auth_web/live/post_live_component/post_live.ex
defmodule AuthWeb.PostLive do
  use Phoenix.LiveComponent
  use Timex

  def update(assigns, session, socket) do
    current_user = Auth.Accounts.get_user_by_session_token(session["user_token"])
    {:ok,
      assign(
        socket,
        assigns,
        current_user: current_user
      )
    }
  end

  # <%= live_component AuthWeb.PostLive, post: post, current_user: @current_user %>
  # <%= live_component @socket, AuthWeb.PostLive, id: "post-#{post.id}", post: post, current_user: @current_user %>

  @doc """
  Converte uma data e hora para uma string formatada.

  ## Parâmetros

    - date: A data a ser formatada.
    - time: A hora a ser formatada.

  ## Exemplos

      iex> format_datetime(~D[2024-01-19], ~T[15:30:00])
      "19 de jan de 2024 • 15:30"
  """
  def format_datetime(date, time) do
    {date, time} = {to_string(date), to_string(time)}

    "#{String.slice(date, 8, 2)} de #{to_name_of_month(date)} de #{String.slice(date, 0, 4)} • #{format_time(time)}"
  end

  @doc false
  defp format_time(time) do
    String.slice(to_string(time), 0..4)
  end

  @doc false
  defp to_name_of_month(date) do
    month = String.slice(to_string(date), 5, 2)
    case month do
      "01" -> "jan"
      "02" -> "fev"
      "03" -> "mar"
      "04" -> "abr"
      "05" -> "mai"
      "06" -> "jun"
      "07" -> "jul"
      "08" -> "ago"
      "09" -> "set"
      "10" -> "out"
      "11" -> "nov"
      "12" -> "dez"
    end
  end

  @doc """
  Calcula o tempo decorrido desde uma postagem com base na data e hora fornecidas.

  ## Parâmetros

    - date: A data da postagem.
    - time: A hora da postagem.

  ## Retorna

    Retorna uma string representando o tempo decorrido desde a postagem, em minutos, horas ou dias.

  ## Exemplos

      iex> DateTime.now("America/Sao_Paulo")
      #DateTime<2024-01-24 14:22:09-03:00 -03 America/Sao_Paulo>

      iex> hours_since_posted(~D[2024-01-24], ~T[13:22:09])
      "1 h"
  """
  def hours_since_posted(date, time) do
    datetime_str = "#{to_string(date)} #{to_string(time)}"
    datetime_posted =
      datetime_str
        |> Timex.parse!("%Y-%m-%d %H:%M:%S", :strftime)
        |> Timex.to_datetime("America/Sao_Paulo")

    current_datetime = Timex.local()

    diff = Timex.diff(current_datetime, datetime_posted, :hours)

    cond do
      diff < 1 ->
        "#{Timex.diff(current_datetime, datetime_posted, :minutes)} min"
      diff >= 24 ->
        "#{Timex.diff(current_datetime, datetime_posted, :days)} d"
      true ->
        "#{diff} h"
    end
  end


end

lib/auth_web/live/profile/profile_live.ex
defmodule AuthWeb.ProfileLive do
  use AuthWeb, :live_view
  alias Auth.{Accounts, Post, Comment}


  @impl true
  def mount(%{"username" => username}, session, socket) do
    if connected?(socket) do
      Post.subscribe()
      Comment.subscribe()
    end
    limite = 6
    user = Accounts.get_user_by_username(username)
    {:ok,
      socket
      |> assign(
        user: user,
        current_user: Accounts.get_user_by_session_token(session["user_token"]),
        posts: Post.get_posts_by_user_id(user.id, limite),
        has_more_posts: true
      )
    }
  end


  @impl true
  def handle_info({:post_created, post}, socket) do
    {:noreply, update(socket, :posts, fn posts -> [post | posts] end)}
  end

  @impl true
  def handle_info({:post_updated, updated_post}, socket) do
    new_posts = Enum.map(socket.assigns.posts, fn post ->
      if post.id == updated_post.id, do: updated_post, else: post
    end)
    {:noreply, assign(socket, posts: new_posts)}
  end


  @impl true
  def handle_event("like", %{"post_id" => post_id}, socket) do
    post = Post.get_post(post_id)
    current_user_id = socket.assigns.current_user.id

    if current_user_id not in post.liked_by do
      Post.inc_like(post, current_user_id) # Add
    else
      Post.dec_like(post, current_user_id) # Remove
    end
    {:noreply, socket}
  end


  @impl true
  def handle_event("save_comment", %{"text-comment" => text_comment, "postid" => post_id}, socket) do
    %{
      user_id: socket.assigns.current_user.id,
      post_id: post_id,
      text: text_comment
    }
    |> Comment.create_comment()
    {:noreply, socket}
  end

  def handle_event("load-more", _params, socket) do
    limite = 6
    last_post_id = socket.assigns.posts |> List.last |> Map.get(:id)
    more_posts = Post.load_more_posts_by_user_id(
      last_post_id,
      socket.assigns.user.id,
      limite
    )

    new_posts = socket.assigns.posts ++ more_posts
    has_more_posts = length(more_posts) == limite
    {:noreply, assign(socket, posts: new_posts, has_more_posts: has_more_posts)}
  end

end

lib/auth_web/live/search/search_live.ex
defmodule AuthWeb.SearchLive do
  use AuthWeb, :live_view
  alias Auth.Accounts


  def mount(_params, _session, socket) do
    limite = 10

    {
      :ok,
      assign(socket,
        search_text: "",
        users: Accounts.get_users(limite), #Accounts.get_random_users(limite)
        has_more_users: true,
        professions: ["Psicólogo(a)", "Fisioterapeuta", "Médico(a)", "Pedagogo(a)", "Fonoaudiólogo(a)", "Terapeuta Ocupacional", "Psicopedagogo(a)", "Psicólogo(a)", "Psiquiatra", "Pediatra", "Assistente social", "Enfermeiro(a)", "Farmacêutico(a)", "Professor(a)"]
      )
    }
  end

  def handle_event("search-submit", %{"q" => search_text}, socket) do
    {:noreply,
      assign(socket,
        search_text: search_text,
        users: Accounts.procura(search_text)
      )
    }
  end

  def handle_event("filter-profession", %{"profession" => profession}, socket) do
    filtered_users = Accounts.procura_por_profissao(profession)
    {:noreply, assign(socket, users: filtered_users, search_text: profession)}
  end

  def handle_event("load-more", _params, socket) do
    limite = 10
    last_user_id = socket.assigns.users |> List.last |> Map.get(:id)
    more_users = Accounts.load_more_users(last_user_id, limite)

    new_users = socket.assigns.users ++ more_users
    has_more_users = length(more_users) == limite
    {:noreply, assign(socket, users: new_users, has_more_users: has_more_users)}
  end


# Procura "automaticamente"
  # In form: <!-- phx-change="search-change" -->
#  def handle_event("search-change", %{"q" => search_text}, socket) do
#    {:noreply,
#      assign(socket,
#        search_text: search_text,
##        users: Auth.Accounts.procura(search_text)
#      )
#    }
#  end

end

lib/auth_web/views/profile_view.ex
defmodule AuthWeb.ProfileView do
  use AuthWeb, :view

  def init(assigns) do
    assigns
  end

end

lib/auth_web/live/profile/profile_live.html.leex
<!-- /profile -->
<section class="m-0 p-0 py-0 space-y-3 max-w-screen w-screen lg:w-2/3"> <!-- -->
    <div class="glass-2 rounded-b-3xl p-8 pb-10 mb-4 grow max-w-screen"> <!-- pb-0 -->
        <div class="flex flex-row md:flex-col justify-center items-center">
            <div class="rounded-full overflow-hidden border-box border-solid border-2 w-40 h-40 bg-white">
                <img alt="Profile image"
                     src=<%= AuthWeb.ImageController.show_img_with_profile_img_path(@user.profile_img_path) %> />
            </div>

            <div class="flex flex-col flex-grow pl-10 md:p-0 gap-0 w-80 justify-center items-center w-full">
                <h3 class="font-bold m-0"><%= "#{@user.name} #{@user.lastname}" %></h3>
                <h2 class="font-semibold text-3xl"><%= @user.profission %></h2>
                <span><%= @user.username %></span>
            </div>
        </div>

        <div class="my-5 w-full h-0.5 bg-gray-300"></div>

        <!-- Sobre -->
        <div class="flex fle-row items-center justify-between font-semibold text-3xl mb-3">
            Sobre
            <%= if @current_user.id == @user.id do %>
                <div class="py-1 px-3 border border-white rounded-lg">
                    <a class="flex flex-row items-center justify-center gap-3 font-normal text-white hover:text-white"
                       href=<%= Routes.user_settings_path(@socket, :edit_profile) %> >

                        <svg xmlns="http://www.w3.org/2000/svg" fill="#ffffff" height="20" width="20" viewBox="0 -960 960 960">
                            <path d="M200-200h57l391-391-57-57-391 391v57Zm-80 80v-170l528-527q12-11 26.5-17t30.5-6q16 0 31 6t26 18l55 56q12 11 17.5 26t5.5 30q0 16-5.5 30.5T817-647L290-120H120Zm640-584-56-56 56 56Zm-141 85-28-29 57 57-29-28Z"/>
                            <title>Editar perfil</title>
                        </svg>
                        <span class="select-none">Editar perfil</span>
                    </a>
                </div>
            <% end %>
        </div>
        <%= if @user.bio do%>
            <div class="mb-4 pl-3 py-2 rounded-md bg-sky-500 hover:bg-sky-300">
                <%= @user.bio %>
            </div>
        <% end %>

        <div class="space-y-4">
            <!-- Profissao -->
            <div class="flex flex-col pl-3 py-2 rounded-md bg-sky-500 hover:bg-sky-300">
                <span class="font-semibold">Profissão:</span>
                <span class="pl-2 text-2xl"><%= @user.profission %></span>
            </div>

            <!-- Endereco -->
            <div class="flex flex-col pl-3 py-2 rounded-md bg-sky-500 hover:bg-sky-300">
                <span class="font-semibold">Endereço:</span>
                <span class="pl-2 text-2xl"><%= @user.endereco %></span>
            </div>

            <!-- Telefone -->
            <div class="flex flex-col pl-3 py-2 rounded-md bg-sky-500 hover:bg-sky-300">
                <span class="font-semibold">Telefone:</span>
                <span class="pl-2 text-2xl"><%= @user.phone %></span>
            </div>

            <!-- E-mail -->
            <div class="flex flex-col pl-3 py-2 rounded-md bg-sky-500 hover:bg-sky-300">
                <span class="font-semibold">E-mail:</span>
                <span class="pl-2 text-2xl"><%= @user.email_prof %></span>
            </div>

            <%= if @user.instagram || @user.linkedin || @user.facebook do %>
            <span class="flex justify-center font-semibold">Redes sociais:</span>
            <div class="flex flex-row items-center justify-evenly">
                <!-- Instagram -->
                <%= if @user.instagram do %>
                    <a target="_blank" rel="noopener noreferrer"
                       href=<%= "https://www.instagram.com/#{String.trim_leading(@user.instagram, "@")}" %> >
                        <svg class="group/instagram" width="30px" height="30px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path class="group-hover/instagram:fill-pink-600" fill="#ffffff" fill-rule="evenodd" clip-rule="evenodd" d="M12 18C15.3137 18 18 15.3137 18 12C18 8.68629 15.3137 6 12 6C8.68629 6 6 8.68629 6 12C6 15.3137 8.68629 18 12 18ZM12 16C14.2091 16 16 14.2091 16 12C16 9.79086 14.2091 8 12 8C9.79086 8 8 9.79086 8 12C8 14.2091 9.79086 16 12 16Z"></path>
                            <path class="group-hover/instagram:fill-pink-600" fill="#ffffff" d="M18 5C17.4477 5 17 5.44772 17 6C17 6.55228 17.4477 7 18 7C18.5523 7 19 6.55228 19 6C19 5.44772 18.5523 5 18 5Z"></path>
                            <path class="group-hover/instagram:fill-pink-600" fill="#ffffff" fill-rule="evenodd" clip-rule="evenodd" d="M1.65396 4.27606C1 5.55953 1 7.23969 1 10.6V13.4C1 16.7603 1 18.4405 1.65396 19.7239C2.2292 20.8529 3.14708 21.7708 4.27606 22.346C5.55953 23 7.23969 23 10.6 23H13.4C16.7603 23 18.4405 23 19.7239 22.346C20.8529 21.7708 21.7708 20.8529 22.346 19.7239C23 18.4405 23 16.7603 23 13.4V10.6C23 7.23969 23 5.55953 22.346 4.27606C21.7708 3.14708 20.8529 2.2292 19.7239 1.65396C18.4405 1 16.7603 1 13.4 1H10.6C7.23969 1 5.55953 1 4.27606 1.65396C3.14708 2.2292 2.2292 3.14708 1.65396 4.27606ZM13.4 3H10.6C8.88684 3 7.72225 3.00156 6.82208 3.0751C5.94524 3.14674 5.49684 3.27659 5.18404 3.43597C4.43139 3.81947 3.81947 4.43139 3.43597 5.18404C3.27659 5.49684 3.14674 5.94524 3.0751 6.82208C3.00156 7.72225 3 8.88684 3 10.6V13.4C3 15.1132 3.00156 16.2777 3.0751 17.1779C3.14674 18.0548 3.27659 18.5032 3.43597 18.816C3.81947 19.5686 4.43139 20.1805 5.18404 20.564C5.49684 20.7234 5.94524 20.8533 6.82208 20.9249C7.72225 20.9984 8.88684 21 10.6 21H13.4C15.1132 21 16.2777 20.9984 17.1779 20.9249C18.0548 20.8533 18.5032 20.7234 18.816 20.564C19.5686 20.1805 20.1805 19.5686 20.564 18.816C20.7234 18.5032 20.8533 18.0548 20.9249 17.1779C20.9984 16.2777 21 15.1132 21 13.4V10.6C21 8.88684 20.9984 7.72225 20.9249 6.82208C20.8533 5.94524 20.7234 5.49684 20.564 5.18404C20.1805 4.43139 19.5686 3.81947 18.816 3.43597C18.5032 3.27659 18.0548 3.14674 17.1779 3.0751C16.2777 3.00156 15.1132 3 13.4 3Z"></path>
                            <title>Instagram</title>
                        </svg>
                    </a>
                <% end %>

                <!-- Linkedin -->
                <%= if @user.linkedin do %>
                    <a target="_blank" rel="noopener noreferrer"
                       href=<%= "https://www.linkedin.com/in#{@user.linkedin}" %> >
                        <svg class="group/linkedin" width="30px" height="30px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path class="group-hover/linkedin:fill-blue-700" fill="#ffffff" d="M6.5 8C7.32843 8 8 7.32843 8 6.5C8 5.67157 7.32843 5 6.5 5C5.67157 5 5 5.67157 5 6.5C5 7.32843 5.67157 8 6.5 8Z"></path>
                            <path class="group-hover/linkedin:fill-blue-700" fill="#ffffff" d="M5 10C5 9.44772 5.44772 9 6 9H7C7.55228 9 8 9.44771 8 10V18C8 18.5523 7.55228 19 7 19H6C5.44772 19 5 18.5523 5 18V10Z"></path>
                            <path class="group-hover/linkedin:fill-blue-700" fill="#ffffff" d="M11 19H12C12.5523 19 13 18.5523 13 18V13.5C13 12 16 11 16 13V18.0004C16 18.5527 16.4477 19 17 19H18C18.5523 19 19 18.5523 19 18V12C19 10 17.5 9 15.5 9C13.5 9 13 10.5 13 10.5V10C13 9.44771 12.5523 9 12 9H11C10.4477 9 10 9.44772 10 10V18C10 18.5523 10.4477 19 11 19Z"></path>
                            <path class="group-hover/linkedin:fill-white" fill="#ffffff" fill-rule="evenodd" clip-rule="evenodd" d="M20 1C21.6569 1 23 2.34315 23 4V20C23 21.6569 21.6569 23 20 23H4C2.34315 23 1 21.6569 1 20V4C1 2.34315 2.34315 1 4 1H20ZM20 3C20.5523 3 21 3.44772 21 4V20C21 20.5523 20.5523 21 20 21H4C3.44772 21 3 20.5523 3 20V4C3 3.44772 3.44772 3 4 3H20Z"></path>
                            <title>Linkedin</title>
                        </svg>
                    </a>
                <% end %>

                <!-- Facebook -->
                <%= if @user.facebook do %>
                    <a target="_blank" rel="noopener noreferrer"
                       href=<%= "https://www.facebook.com/#{String.trim_leading(@user.facebook, "/")}" %> >
                        <svg class="group/facebook" width="30px" height="30px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path class="group-hover/facebook:fill-blue-800" fill="#ffffff" fill-rule="evenodd" clip-rule="evenodd" d="M20 1C21.6569 1 23 2.34315 23 4V20C23 21.6569 21.6569 23 20 23H4C2.34315 23 1 21.6569 1 20V4C1 2.34315 2.34315 1 4 1H20ZM20 3C20.5523 3 21 3.44772 21 4V20C21 20.5523 20.5523 21 20 21H15V13.9999H17.0762C17.5066 13.9999 17.8887 13.7245 18.0249 13.3161L18.4679 11.9871C18.6298 11.5014 18.2683 10.9999 17.7564 10.9999H15V8.99992C15 8.49992 15.5 7.99992 16 7.99992H18C18.5523 7.99992 19 7.5522 19 6.99992V6.31393C19 5.99091 18.7937 5.7013 18.4813 5.61887C17.1705 5.27295 16 5.27295 16 5.27295C13.5 5.27295 12 6.99992 12 8.49992V10.9999H10C9.44772 10.9999 9 11.4476 9 11.9999V12.9999C9 13.5522 9.44771 13.9999 10 13.9999H12V21H4C3.44772 21 3 20.5523 3 20V4C3 3.44772 3.44772 3 4 3H20Z"></path>
                            <title>Facebook</title>
                        </svg>
                    </a>
                <% end %>
            </div>
            <% end %>
        </div>
    </div>


    <div id="infinite-scroll-hook" class="space-y-3" phx-hook="InfiniteScroll">
        <%= if Enum.count(@posts) >= 1 do %>
            <!-- Render post -->
            <%= for post <- @posts do %>
                <%= live_component AuthWeb.PostLive, post: post, current_user: @current_user %>
            <% end %>

            <%= if @has_more_posts do %>
                <!-- Loading Spinner HTML -->
                <div class="flex my-4 justify-center items-center" id="loading-more-posts loading">
                    <div class="loader ease-linear rounded-full border-2 border-t-2 border-gray-200 h-16 w-16">
                    </div>
                </div>
            <% else %>
                <div class="flex my-2 items-center justify-center" id="no-more-posts">
                    Não há mais posts para mostrar.
                </div>
            <% end %>
        <% end %>
    </div>

</section>